spring:
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
  mvc:
    static-path-pattern: /static/**


  datasource:
    url: jdbc:h2:tcp://localhost/~/bookreport
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace




